server:
  host: "0.0.0.0"
  port: 8080

redis:
  addr: "localhost:6379"
  password: ""

games:
  - id: "mmo"
    game_backend:
      host: "localhost"
      port: 9001
      pool_size: 100
    chat_backend:
      host: "localhost"
      port: 9002
      pool_size: 1  # 修改为 1，解决多连接消息丢失问题
